steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/project-aa7ee149-5e29-4eb4-8bc/cloud-run-source-deploy/fixmart-manufacturing-pl', '.']
images:
  - 'europe-west1-docker.pkg.dev/project-aa7ee149-5e29-4eb4-8bc/cloud-run-source-deploy/fixmart-manufacturing-pl'
options:
  logging: CLOUD_LOGGING_ONLY
